version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      #POSTGRES_DB: poke_store
      POSTGRES_DB: accounts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"

  app:
    build: .
    command: sh -c "npm install && nodemon ./src/app.js"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: docker
      #DATABASE_NAME: poke_store
      DATABASE_NAME: accounts